In [ ]:
# (1) Download databricks.spark.xml library 
# (2) https://repo1.maven.org/maven2/com/databricks/spark-xml_2.12/0.12.0/spark-xml_2.12-0.12.0.jar
# (3) Upload jar file to HDFS root
from pyspark.sql import SparkSession
from pyspark.sql.functions import *
warehouse_location = 'hdfs://namenode:8020/warehouse'
spark = SparkSession \
    .builder \
    .appName("Python Spark SQL Hive integration example") \
    .config("spark.sql.warehouse.dir", warehouse_location) \
    .config("hive.metastore.uris", "thrift://hive-metastore:9083") \
    .enableHiveSupport() \
    .getOrCreate()

In [ ]:
spark.version

In [ ]:
sc = spark.sparkContext

In [ ]:
hdfs_path = "hdfs://namenode:8020//test/66aa6f41-5cd3-450a-9672-9e80e6fba624"
hdfs_path2 = "hdfs://namenode:8020//raw/fails/00ffbf9a-e13b-43b8-82b2-fe3f71bd5acd"

In [ ]:
multiline_df = spark.read.option("multiline","true") \
      .json((hdfs_path)).select("results")
multiline_df.show()

In [ ]:
multiline_df2 = spark.read.option("multiline","true") \
      .json((hdfs_path2)).select("results")
multiline_df2.show()

In [ ]:
from pyspark.sql.types import *

In [ ]:
df2 = multiline_df.withColumn("results", explode("results")) \
    .withColumn("sensor_created_at", col("results")["sensor_created_at"].cast("timestamp")) \
    .withColumn("sensor_event_type", col("results")["sensor_event_type"].cast("string")) \
    .withColumn("sensor_id_cycle", col("results")["sensor_id_cycle"].cast("integer")) \
    .withColumn("sensor_ip", col("results")["sensor_ip"].cast("string")) \
    .withColumn("sensor_unique_id", col("results")["sensor_unique_id"].cast("string")) \
    .withColumn("sensor_value_humidity", col("results")["sensor_value_humidity"].cast("integer")) \
    .withColumn("sensor_value_temperature_motor1", col("results")["sensor_value_temperature_motor1"].cast("integer")) \
    .withColumn("sensor_value_temperature_motor2", col("results")["sensor_value_temperature_motor2"].cast("integer")) \
    .withColumn("sensor_value_temperature_motor3", col("results")["sensor_value_temperature_motor3"].cast("integer")) \
    .withColumn("sensor_value_vibrationhz_x", col("results")["sensor_value_vibrationhz_x"].cast("integer")) \
    .withColumn("sensor_value_vibrationhz_y", col("results")["sensor_value_vibrationhz_y"].cast("integer")) \
    .withColumn("sensor_value_vibrationhz_z", col("results")["sensor_value_vibrationhz_z"].cast("integer")) \
    .withColumn("value_noise_dba_motor1", col("results")["value_noise_dba_motor1"].cast("integer")) \
    .withColumn("value_noise_dba_motor2", col("results")["value_noise_dba_motor2"].cast("integer")) \
    .withColumn("value_noise_dba_motor3", col("results")["value_noise_dba_motor3"].cast("integer")) \
    .drop("results") \
    .orderBy("sensor_created_at")

In [ ]:
df3 = multiline_df2.withColumn("results", explode("results")) \
    .withColumn("falha_created_at", col("results")["falha_created_at"].cast("timestamp")) \
    .withColumn("falha_id_falha", col("results")["falha_id_falha"].cast("string")) \
    .withColumn("falha_ip", col("results")["falha_ip"].cast("string")) \
    .withColumn("falha_hostname", col("results")["falha_hostname"].cast("string")) \
    .withColumn("falha_event_type", col("results")["falha_event_type"].cast("string")) \
    .withColumn("falha_tipo_falha", col("results")["falha_tipo_falha"].cast("string")) \
    .withColumn("falha_error_code", col("results")["falha_error_code"].cast("string")) \
    .withColumn("falha_error_description", col("results")["falha_error_description"].cast("string")) \
    .drop("results") \
    .orderBy("falha_created_at")

In [ ]:
_df_sensor = df2.toPandas()
_df_falhas = df3.toPandas()

In [ ]:
_df_sensor

In [ ]:
_df_sensor[_df_sensor["sensor_created_at"] == "2021-11-22 09:48:55"]

In [ ]:
pip install plotly

In [ ]:
import plotly.express as px

fig = px.line(_df_sensor, x='sensor_created_at', y="sensor_value_vibrationhz_z")
fig.show()

In [ ]:
fig = px.line(_df_sensor, x='sensor_created_at', y="sensor_value_vibrationhz_x")
fig.show()

In [ ]:
_df_falhas

In [ ]:
df2.printSchema()

In [ ]:
df3.printSchema()

In [24]:
_df_sensor.dtypes

sensor_created_at                  datetime64[ns]
sensor_event_type                          object
sensor_id_cycle                             int32
sensor_ip                                  object
sensor_unique_id                           object
sensor_value_humidity                       int32
sensor_value_temperature_motor1             int32
sensor_value_temperature_motor2             int32
sensor_value_temperature_motor3             int32
sensor_value_vibrationhz_x                  int32
sensor_value_vibrationhz_y                  int32
sensor_value_vibrationhz_z                  int32
value_noise_dba_motor1                      int32
value_noise_dba_motor2                      int32
value_noise_dba_motor3                      int32
dtype: object

In [25]:
_df_falhas.dtypes

falha_created_at           datetime64[ns]
falha_id_falha                     object
falha_ip                           object
falha_hostname                     object
falha_event_type                   object
falha_tipo_falha                   object
falha_error_code                   object
falha_error_description            object
dtype: object

In [103]:
import pandas as pd
import xlrd
import numpy as np
import matplotlib.pyplot as plt

In [104]:
df44

49.44657036981018

In [105]:
_df_sensor.describe()

,sensor_id_cycle,sensor_value_humidity,sensor_value_temperature_motor1,sensor_value_temperature_motor2,sensor_value_temperature_motor3,sensor_value_vibrationhz_x,sensor_value_vibrationhz_y,sensor_value_vibrationhz_z,value_noise_dba_motor1,value_noise_dba_motor2,value_noise_dba_motor3,average,averagetemp,averagenoise
count,13223.000000,13223.00000,13223.000000,13223.000000,13223.000000,13223.000000,13223.000000,13223.000000,13223.000000,13223.000000,13223.000000,13223.000000,13223.000000,13223.000000
mean,2.994631,49.44657,16.928685,18.578537,19.492021,15.437420,15.500870,15.510172,44.674809,44.488089,44.655751,18.333081,18.333081,44.606216
std,1.410642,20.26962,7.228407,8.080858,8.660826,3.440529,3.485039,3.444664,14.444380,14.439317,14.371118,4.607391,4.607391,8.310872
min,1.000000,15.00000,5.000000,5.000000,5.000000,10.000000,10.000000,10.000000,20.000000,20.000000,20.000000,5.333333,5.333333,21.000000
25%,2.000000,32.00000,11.000000,12.000000,12.000000,12.000000,12.000000,13.000000,32.000000,32.000000,32.000000,15.000000,15.000000,38.666667
50%,3.000000,50.00000,17.000000,19.000000,19.000000,15.000000,15.000000,16.000000,45.000000,44.000000,45.000000,18.333333,18.333333,44.666667
75%,4.000000,67.00000,23.000000,26.000000,27.000000,18.000000,19.000000,18.000000,57.000000,57.000000,57.000000,21.666667,21.666667,50.666667
max,5.000000,84.00000,29.000000,32.000000,34.000000,21.000000,21.000000,21.000000,69.000000,69.000000,69.000000,31.666667,31.666667,68.000000

In [106]:
dfmedia = _df_sensor

In [107]:
dfmedia['averagetemp'] = dfmedia[['sensor_value_temperature_motor1','sensor_value_temperature_motor2','sensor_value_temperature_motor3']].mean(axis=1)

In [108]:
dfmedia['averagenoise'] = dfmedia[['value_noise_dba_motor1','value_noise_dba_motor2','value_noise_dba_motor3']].mean(axis=1)

In [109]:
dfmedia

,sensor_created_at,sensor_event_type,sensor_id_cycle,sensor_ip,sensor_unique_id,sensor_value_humidity,sensor_value_temperature_motor1,sensor_value_temperature_motor2,sensor_value_temperature_motor3,sensor_value_vibrationhz_x,sensor_value_vibrationhz_y,sensor_value_vibrationhz_z,value_noise_dba_motor1,value_noise_dba_motor2,value_noise_dba_motor3,average,averagetemp,averagenoise,Dates,Time
0,00:00:00,sensor,2,172.27.0.10,daaed3b5-ed2a-4630-9014-2a2e384e8fbd,68,23,16,33,18,21,12,55,25,32,24.000000,24.000000,37.333333,NaT,NaT
1,00:00:00,sensor,2,172.27.0.10,7b89ae17-fccc-4bf8-8600-8c7cf98f5d54,74,20,20,17,14,13,18,29,30,54,19.000000,19.000000,37.666667,NaT,NaT
2,00:00:00,sensor,2,172.27.0.10,6b68370d-012a-4b3e-b23c-0a1fd5479c75,29,14,21,6,12,12,14,58,69,35,13.666667,13.666667,54.000000,NaT,NaT
3,00:00:00,sensor,5,172.27.0.10,f3fe7785-29ce-4f8c-9df9-b21f4f15f115,33,22,11,11,15,14,11,20,58,35,14.666667,14.666667,37.666667,NaT,NaT
4,00:00:00,sensor,5,172.27.0.10,f4e50c89-df63-48e7-8aad-d569a8240368,53,14,5,11,12,15,17,51,35,45,10.000000,10.000000,43.666667,NaT,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13218,00:00:00,sensor,2,172.27.0.10,168ded9d-e8d5-4139-bc8b-7b4da6cb537e,84,23,22,12,17,16,20,21,43,23,19.000000,19.000000,29.000000,NaT,NaT
13219,00:00:00,sensor,2,172.27.0.10,6f906165-1129-4b50-a06b-945b2b49f85c,42,17,16,29,12,15,13,25,22,69,20.666667,20.666667,38.666667,NaT,NaT
13220,00:00:00,sensor,2,172.27.0.10,f90156bd-7429-41db-9349-9c92972a0972,60,5,31,22,17,21,18,38,23,23,19.333333,19.333333,28.000000,NaT,NaT
13221,00:00:00,sensor,5,172.27.0.10,d86bc11f-f963-4943-900c-84af58eb360d,15,17,9,17,13,15,15,69,37,52,14.333333,14.333333,52.666667,NaT,NaT
13222,00:00:00,sensor,3,172.27.0.10,86feff7e-2fea-43c5-95ea-a8f7557c1100,69,29,17,27,15,18,14,36,57,63,24.333333,24.333333,52.000000,NaT,NaT

In [111]:
from pyspark.sql import Row
from pyspark.sql.functions import explode, min, max, col, round, hour, minute, count, dayofmonth, month, substring, avg
from pyspark.sql.types import IntegerType
from pyspark.sql.types import TimestampType

In [114]:
_df_sensor = _df_sensor.withColumn("temp_dayOfMonth", dayofmonth("sensor_created_at"))
_df_sensor = dataframe.withColumn("temp_month", month("sensor_created_at"))
_df_sensor = dataframe.withColumn("temp_hour", substring("sensor_created_at", 11, 13))
_df_sensor = dataframe.withColumn("temp_date", substring("sensor_created_at", 0, 10))

AttributeError: 'DataFrame' object has no attribute 'withColumn'